Homework 21
Otus-DevOps-2017-11/VARyumin_microservices pull request #7
Opened 2018-04-02 07:57 UTC by varyumin

Please check my homework 21.  "Introduction to monitoring. Monitoring system."
My docker registry https://hub.docker.com/u/varyumin/

2018-04-04 13:08 UTC, Nklya requested changes
Добрый день.

Я не вижу в этом PR следов ДЗ по мониторингу.

2018-04-04 13:08 UTC, Nklya commented on docker/docker-compose.yml
> +      - reddit.env
Зачем отдельный reddit.env и его везде прописывать, если бы он подтянул без лишнего кода `.env` файл?

2018-04-04 13:21 UTC, varyumin commented on docker/docker-compose.yml
> +      - reddit.env
А какие должны были быть следы ?

2018-04-04 13:24 UTC, Nklya commented
> А какие должны были быть следы ?

В первом ДЗ по мониторингу делается реорганизация директорий, добавляется в композ прометеус и экспортеры, добавляется докерфайл прометеуса.

2018-04-04 13:36 UTC, varyumin commented
Бред какой то где то так жестко накосячил даже нет README по 21 заданию хотя в следующем PR по 23 есть все. Ок понял щас переоформлю

2018-04-04 14:04 UTC, varyumin commented
Поправил

2018-04-04 14:08 UTC, Nklya commented
Нет, сюда же все попало

2018-04-05 11:58 UTC, varyumin commented
Исправил можете проверить!?

2018-04-05 12:04 UTC, Nklya commented
Да, сегодня-завтра посмотрю

2018-04-05 14:45 UTC, Nklya approved these changes
Добрый день.

Владимир, условия ДЗ выполнены, все выглядит ок 👍 

Единственное, что .env не стоило коммитить.

2018-04-05 14:45 UTC, Nklya commented on .gitignore
>  *.pyc
.env нужно было добавить в .gitignore и вычистить из репы.

2018-04-06 05:56 UTC, merged